---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-nginx-sample
spec:
  selector:
    matchLabels:
      app: ds-nginx-sample
  template:
    metadata:
      labels:
        app: ds-nginx-sample
    spec:
      containers:
        - image: nginx:latest
          name: nginx
